### ISSUE TITLE
_process_oob should be put in the event queue based on sigio and not a timer

### ISSUE THREAD

**Issue by marcuschangarm** [ARMmbed/esp8266-driver#119]
### Description

Currently, `_process_oob` is being called from a recurring task in the event queue that runs every 2 second. It would be more efficient if the task was only inserted into the queue whenever the UART sigio callback is triggered similar to how the cellular AT handler is doing it:

https://github.com/ARMmbed/mbed-os/blob/master/features/cellular/framework/AT/ATHandler.cpp#L222-L229

### Issue request type

[ ] Question  
[x] Enhancement  
[ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-149*
