### ISSUE TITLE
Doesn't compile against mbed-os master

### ISSUE THREAD

**Issue by tommikas** [ARMmbed/esp8266-driver#12]
```
[ERROR] In file included from ./esp8266-driver/ESP8266Interface.cpp:18:0:
./esp8266-driver/ESP8266Interface.h:20:41: fatal error: network-socket/NetworkStack.h: No such file or directory
 #include "network-socket/NetworkStack.h"
```

Should be `netsock/NetworkStack.h` now.

**Comment by geky** [comment]
Thanks for reporting this. However, there is another set of changes staged for the WiFiInterface that will deeply impact the implementation of the esp8266-driver: https://github.com/ARMmbed/mbed-os/pull/2874

Also there is the concern of breaking the version used for the release (which has been problematic https://github.com/ARMmbed/esp8266-driver/issues/7). Perhaps this repo needs a dev branch?

**Comment by tommikas** [comment]
>Perhaps this repo needs a dev branch?

Whatever works the best. We need to be able to use the driver with mbed-os master, so as long as that's possible it's fine.

Speaking of incoming changes, are the currently [unsupported socket operations](https://github.com/ARMmbed/esp8266-driver/blob/master/ESP8266Interface.cpp#L134-L137) going to be implemented at some point?

**Comment by geky** [comment]
The unsupported operations were actually due to technical limitations in the 0.2 version of the esp8266 firmware. Support requires a bit of effort in updating to 2.0 but is planned.

**Comment by tommikas** [comment]
I figured there might have been something like that. Nice to hear it's coming :)

**Comment by tommikas** [comment]
Closing, since this has now been fixed.
