### ISSUE TITLE
Fold together the ESP8266 and ESP8266Interface

### ISSUE THREAD

**Issue by geky** [ARMmbed/esp8266-driver#29]
For a bit of history, the ESP8266 class existed before the NetworkInterface classes were designed. Now that the NetworkInterface has become pretty well established, the ESP8266 class only exists as a vestigial organ that we can probably remove.

cc @MarceloSalazar, @kegilbert

**Comment by SeppoTakalo** [comment]
Closing as this is just refactoring without real benefits. Code has been pretty stable for quite long now, no need to change.

**Comment by geky** [comment]
Agreed :+1:
