### ISSUE TITLE
Add a set_speed() get_speed() interface

### ISSUE THREAD

**Issue by dlfryar** [ARMmbed/esp8266-driver#47]
Need a configuration parameter and interface to get/set the speed/baud of the ESP.  Similar pattern to Ethernet where it may be set to 10/100/1000.

Example user had it running at 230Kbps.  Default value is ESP8266_DEFAULT_BAUD_RATE   115200
https://os.mbed.com/users/4180_1/notebook/using-the-esp8266-with-the-mbed-lpc1768/

I'm not sure if mbed_app.json is the best place for this, or a driver level setting.

**Comment by dlfryar** [comment]
Test branch

https://github.com/ARMmbed/esp8266-driver/tree/g-custom-baud-rate

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-500

**Comment by dlfryar** [comment]
Closing after the download issue was isolated to other subsystems.
