### ISSUE TITLE
ESP8266 broadcast bogus access point names

### ISSUE THREAD

**Issue by SeppoTakalo** [ARMmbed/esp8266-driver#49]
By default the device is either in AP mode or AP+client mode.

Driver seem to touch only the current setting `AT+CWMODE_CUR`, not the default one `AT+CWMODE_DEF`

This should be changed so that by default, it will mode fixed to client mode and that setting should be saved to flash using `AT+CWMODE_DEF`

Reference: [ESP8266 Instruction set ](https://www.espressif.com/sites/default/files/documentation/4a-esp8266_at_instruction_set_en.pdf)

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-498

**Comment by SeppoTakalo** [comment]
Fixed in https://github.com/ARMmbed/esp8266-driver/commit/00e0174a6568344920183b11321ff1ed199386e8
