### ISSUE TITLE
Driver does not reconnect

### ISSUE THREAD

**Issue by lauri-piikivi** [ARMmbed/esp8266-driver#84]
https://github.com/ARMmbed/esp8266-driver/blob/1d0be7817429de0fcdf9738a3d3fa2abce9e6297/ESP8266/ESP8266.cpp#L835

It is target state for network interfaces that the drivers try to reconnect if connection drops. Seems the driver does not do that. In the wanted operation, the state is is informed to application and the driver tries to reconnect.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1668

**Comment by VeijoPesonen** [comment]
Noted, to be implemented. @SeppoTakalo comments?

**Comment by VeijoPesonen** [comment]
Addressed in ARMmbed/mbed-os#8853. Notice that the fix is to be found from the Mbed OS in-tree driver and it's not going to be added on this deprecated repository.
