### ISSUE TITLE
Len vs amount check

### ISSUE THREAD

**Issue by lauri-piikivi** [ARMmbed/esp8266-driver#85]
https://github.com/ARMmbed/esp8266-driver/blob/1d0be7817429de0fcdf9738a3d3fa2abce9e6297/ESP8266/ESP8266.cpp#L560

Seems there is no check if the actual data Len is bigger than amount. AT command spec doesn't seem to prevent this

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1667
