### ISSUE TITLE
strange id comparison

### ISSUE THREAD

**Issue by lauri-piikivi** [ARMmbed/esp8266-driver#86]
https://github.com/ARMmbed/esp8266-driver/blob/1d0be7817429de0fcdf9738a3d3fa2abce9e6297/ESP8266/ESP8266.cpp#L571

I do not really understand this [id].id != id, if the socket is closed, should we check the connected status?

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1666

**Comment by VeijoPesonen** [comment]
Redundancy due to the fact I needed to store somewhere the information if the socket is TCP or UDP one. I could change this to something like.
`if (!_socket_open[id].open) {`

**Comment by VeijoPesonen** [comment]
Fix merged, closing the issue.
