### ISSUE TITLE
Country code needs to be set

### ISSUE THREAD

**Issue by lauri-piikivi** [ARMmbed/esp8266-driver#90]
e.g. AT+CWCOUNTRY_CUR
The channel usage may differ in US an Europe, so this should be done

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1687

**Comment by VeijoPesonen** [comment]
PR ARMmbed/mbed-os#9927 created to address this issue. Please start to use the in-tree driver in case you have been relying on this external repository.

**Comment by VeijoPesonen** [comment]
PR merged.
