### ISSUE TITLE
Why this differs from UDP

### ISSUE THREAD

**Issue by lauri-piikivi** [ARMmbed/esp8266-driver#91]
https://github.com/ARMmbed/esp8266-driver/blob/1d0be7817429de0fcdf9738a3d3fa2abce9e6297/ESP8266/ESP8266.cpp#L426

UDP open returns status, not just bool. And if the socket is now open, we return false for TCP, which the client probably can not match to already open

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1686

**Comment by SeppoTakalo** [comment]
Fixed in:
https://github.com/ARMmbed/mbed-os/commit/8dd6a5d039ff4801a6406b2f11dd3b645a0a208d
