### ISSUE TITLE
Missing from following else?

### ISSUE THREAD

**Issue by lauri-piikivi** [ARMmbed/esp8266-driver#93]
https://github.com/ARMmbed/esp8266-driver/blob/1d0be7817429de0fcdf9738a3d3fa2abce9e6297/ESP8266/ESP8266.cpp#L717

Should the line be in the else statement following this if?

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1690

**Comment by VeijoPesonen** [comment]
By a quick look seems to be that you found a bug, thanks.

**Comment by VeijoPesonen** [comment]
Fix merged.
