### ISSUE TITLE
Should this call the underlying udp or tcp open?

### ISSUE THREAD

**Issue by lauri-piikivi** [ARMmbed/esp8266-driver#94]
https://github.com/ARMmbed/esp8266-driver/blob/1d0be7817429de0fcdf9738a3d3fa2abce9e6297/ESP8266Interface.cpp#L319

Are the udp_open and tcp_open called somewhere? I could not easily find. Might be that this socket_open should call the correct one based on proto parameter?

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1689

**Comment by VeijoPesonen** [comment]
Those are called from socket_connect(). With UDP socket you're not supposed to call connect but that is done internally. It's a bit weird way how to handle things but works. Please close the ticket if the answer is satisfactory.

**Comment by SeppoTakalo** [comment]
Closing.
No reply back from Lauri, so I'm assuming the answer to be satisfactory.
